name: Daily Commit Workflow

on:
  schedule:
    # This runs at 12:00 UTC every day
    - cron: "0 12 * * *"
  workflow_dispatch: # Allow manual triggers

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --local user.email "21f2000588@ds.study.iitm.ac.in"
          git config --local user.name "DevSync Bot"

      - name: Add a daily commit
        run: |
          echo "This is an automated daily commit" >> daily-commit.txt
          git add daily-commit.txt
          git commit -m "Daily commit [skip ci]" || exit 0
          git push

