name: "21f2000588@ds.study.iitm.ac.in"

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual trigger

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: 21f2000588@ds.study.iitm.ac.in
        uses: actions/checkout@v4

      - name: Set up Git configuration
        run: |
          git config --local user.email "21f2000588@ds.study.iitm.ac.in"
          git config --local user.name "21f2000588"  # Override GitHub username

      - name: Create a file with a daily commit message
        run: |
          echo "This is an automated daily commit" >> daily-commit.txt

      - name: Commit changes
        run: |
          git add daily-commit.txt
          git commit -m "Daily commit [skip ci]" || exit 0  # Skip if no changes

      - name: Pull latest changes from main
        run: |
          git pull https://github.com/${{ github.repository }}.git main --rebase

      - name: Push changes to repository
        run: |
          git push https://github.com/${{ github.repository }}.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the token to authenticate the push
