name: Daily Commit

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allow manual triggers

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git configuration
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "GitHub Actions"

      - name: Create a file with a daily commit message
        run: |
          echo "This is an automated daily commit" >> daily-commit.txt

      - name: Commit changes
        run: |
          git add daily-commit.txt
          git commit -m "Daily commit [skip ci]" || exit 0  # Skip if there are no changes

      - name: Push changes to repository
        run: |
          git push https://github.com/${{ github.repository }}.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the token to authenticate the push
